-- migration_foods.sql
-- Thêm 100 thực phẩm Việt Nam vào live database
-- Chạy: PGPASSWORD=<pass> psql -U postgres -h localhost -p 5432 -d nutrition_system -f src/db/migration_foods.sql
-- Idempotent: bỏ qua nếu tên thực phẩm đã tồn tại

-- === TINH BỘT & NGŨ CỐC ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bún tươi', 'Rice vermicelli', 109, 2.5, 25.2, 0.2, 0.3, 65, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bún tươi');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bánh phở', 'Pho noodles', 108, 2.4, 24.8, 0.2, 0.2, 67, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bánh phở');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Mì trứng khô', 'Dry egg noodles', 358, 13.0, 67.0, 4.5, 2.5, 55, TRUE, TRUE, TRUE, FALSE, FALSE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Mì trứng khô');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bánh mì trắng', 'White bread', 265, 8.0, 50.0, 3.2, 2.0, 75, FALSE, TRUE, TRUE, FALSE, FALSE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bánh mì trắng');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Khoai tây', 'Potato', 77, 2.0, 17.0, 0.1, 2.2, 70, FALSE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Khoai tây');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Ngô (bắp)', 'Corn', 96, 3.4, 21.0, 1.5, 2.4, 52, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Ngô (bắp)');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sắn/Khoai mì', 'Cassava', 160, 1.4, 38.1, 0.3, 1.8, 65, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sắn/Khoai mì');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Miến dong', 'Glass noodles', 351, 0.1, 86.1, 0.1, 0.5, 65, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Miến dong');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Khoai môn', 'Taro', 112, 1.5, 26.5, 0.2, 4.1, 55, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Khoai môn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bánh chưng', 'Sticky rice cake', 175, 5.8, 29.0, 4.2, 1.0, 65, FALSE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bánh chưng');

-- === THỊT & GIA CẦM ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt lợn nạc', 'Lean pork', 143, 21.5, 0.0, 6.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt lợn nạc');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt bò', 'Beef', 250, 26.0, 0.0, 15.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt bò');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sườn lợn', 'Pork ribs', 278, 18.0, 0.0, 22.5, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sườn lợn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt gà đùi', 'Chicken thigh', 209, 18.0, 0.0, 15.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt gà đùi');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt vịt', 'Duck meat', 337, 19.0, 0.0, 28.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt vịt');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt dê', 'Goat meat', 143, 27.0, 0.0, 3.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt dê');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Gan lợn', 'Pork liver', 134, 20.6, 3.8, 3.7, 0.0, 0, TRUE, FALSE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Gan lợn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tim lợn', 'Pork heart', 119, 17.1, 1.3, 4.8, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tim lợn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Lòng lợn', 'Pork intestine', 166, 9.5, 1.0, 14.0, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Lòng lợn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Xúc xích', 'Pork sausage', 301, 12.0, 3.5, 27.0, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Xúc xích');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt heo quay', 'Roast pork', 305, 20.0, 8.0, 22.0, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt heo quay');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt bò khô', 'Dried beef jerky', 350, 55.0, 8.0, 11.0, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt bò khô');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Chả lụa', 'Vietnamese pork roll', 185, 15.5, 4.0, 12.0, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Chả lụa');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thịt gà xé', 'Shredded chicken', 170, 32.0, 0.0, 4.5, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thịt gà xé');

-- === HẢI SẢN ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá tra', 'Pangasius', 102, 16.0, 0.0, 4.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá tra');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá thu', 'Mackerel', 205, 19.0, 0.0, 13.5, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá thu');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá ngừ', 'Tuna', 144, 23.0, 0.0, 5.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá ngừ');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá rô phi', 'Tilapia', 96, 20.0, 0.0, 1.7, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá rô phi');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá chép', 'Carp', 127, 17.8, 0.0, 5.6, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá chép');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tôm sú', 'Black tiger shrimp', 99, 18.1, 1.0, 2.2, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tôm sú');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tôm thẻ', 'White shrimp', 85, 18.0, 0.0, 1.0, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tôm thẻ');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Mực ống', 'Squid', 92, 15.6, 3.1, 1.4, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Mực ống');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cua biển', 'Sea crab', 87, 18.1, 0.0, 1.1, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cua biển');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sò huyết', 'Blood cockle', 74, 11.6, 4.7, 0.9, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sò huyết');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Hàu', 'Oyster', 68, 7.1, 4.3, 2.5, 0.0, 0, TRUE, TRUE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Hàu');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá cơm khô', 'Dried anchovy', 295, 59.0, 0.0, 5.5, 0.0, 0, TRUE, FALSE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá cơm khô');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cá mòi hộp', 'Canned sardine', 208, 24.6, 0.0, 11.5, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cá mòi hộp');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tôm khô', 'Dried shrimp', 298, 62.0, 0.0, 2.9, 0.0, 0, TRUE, FALSE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tôm khô');

-- === RAU CỦ ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cải thảo', 'Napa cabbage', 16, 1.2, 3.2, 0.2, 1.2, 10, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cải thảo');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cải xanh', 'Mustard greens', 27, 2.7, 4.3, 0.4, 2.0, 10, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cải xanh');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Rau cải ngọt', 'Bok choy', 13, 1.5, 2.2, 0.2, 1.0, 10, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Rau cải ngọt');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Mướp đắng', 'Bitter melon', 17, 1.0, 3.7, 0.2, 2.8, 15, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Mướp đắng');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bầu', 'Bottle gourd', 14, 0.6, 3.4, 0.0, 0.5, 15, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bầu');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bí đỏ', 'Pumpkin', 26, 1.0, 6.5, 0.1, 0.5, 65, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bí đỏ');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cà chua', 'Tomato', 18, 0.9, 3.9, 0.2, 1.2, 15, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cà chua');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cà rốt', 'Carrot', 41, 0.9, 9.6, 0.2, 2.8, 47, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cà rốt');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đậu cô ve', 'Green beans', 31, 1.8, 7.1, 0.1, 2.7, 30, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đậu cô ve');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đậu Hà Lan', 'Green peas', 81, 5.4, 14.5, 0.4, 5.7, 51, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đậu Hà Lan');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Giá đỗ', 'Bean sprouts', 30, 3.0, 5.9, 0.2, 1.8, 25, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Giá đỗ');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Hành tây', 'Onion', 40, 1.1, 9.3, 0.1, 1.7, 10, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Hành tây');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tỏi', 'Garlic', 149, 6.4, 33.1, 0.5, 2.1, 30, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tỏi');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Gừng', 'Ginger', 80, 1.8, 17.8, 0.8, 2.0, 25, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Gừng');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Rau húng quế', 'Thai basil', 23, 3.2, 2.7, 0.6, 1.6, 0, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Rau húng quế');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Rau ngò rí', 'Cilantro', 23, 2.1, 3.7, 0.5, 2.8, 0, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Rau ngò rí');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Nấm rơm', 'Straw mushroom', 22, 2.1, 3.5, 0.3, 1.2, 15, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Nấm rơm');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Nấm hương', 'Shiitake mushroom', 34, 2.2, 6.8, 0.5, 2.5, 15, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Nấm hương');

-- === TRÁI CÂY ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Xoài', 'Mango', 65, 0.5, 17.0, 0.3, 1.8, 56, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Xoài');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Ổi', 'Guava', 68, 2.6, 14.3, 1.0, 5.4, 12, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Ổi');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đu đủ', 'Papaya', 43, 0.5, 11.0, 0.3, 1.7, 59, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đu đủ');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Dưa hấu', 'Watermelon', 30, 0.6, 7.6, 0.2, 0.4, 72, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Dưa hấu');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Dứa', 'Pineapple', 50, 0.5, 13.1, 0.1, 1.4, 66, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Dứa');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cam', 'Orange', 47, 0.9, 11.8, 0.1, 2.4, 40, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cam');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bưởi', 'Pomelo', 38, 0.8, 9.6, 0.1, 1.0, 25, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bưởi');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Thanh long', 'Dragon fruit', 60, 1.2, 13.2, 0.4, 3.0, 50, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Thanh long');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Nhãn', 'Longan', 60, 1.3, 15.1, 0.1, 1.1, 52, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Nhãn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Vải', 'Lychee', 66, 0.8, 16.5, 0.4, 1.3, 57, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Vải');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sầu riêng', 'Durian', 147, 1.5, 27.1, 5.3, 3.8, 49, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sầu riêng');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bơ (quả)', 'Avocado', 160, 2.0, 8.5, 14.7, 6.7, 15, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bơ (quả)');

-- === LEGUMES & ĐẬU ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đậu đen', 'Black bean', 341, 21.6, 62.4, 1.4, 15.5, 35, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đậu đen');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đậu xanh', 'Mung bean', 347, 23.9, 62.6, 1.2, 16.3, 25, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đậu xanh');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đậu đỏ', 'Red kidney bean', 333, 22.5, 60.0, 0.8, 15.2, 29, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đậu đỏ');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đậu phộng', 'Peanut', 567, 25.8, 16.1, 49.2, 8.5, 14, TRUE, TRUE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đậu phộng');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sữa đậu nành', 'Soy milk', 54, 3.3, 6.3, 1.8, 0.0, 30, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sữa đậu nành');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tương đậu nành', 'Soy sauce', 60, 10.5, 5.6, 0.1, 0.8, 0, TRUE, FALSE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tương đậu nành');

-- === SỮA & TRỨNG ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sữa tươi nguyên kem', 'Whole milk', 61, 3.2, 4.8, 3.3, 0.0, 27, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sữa tươi nguyên kem');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Sữa đặc có đường', 'Sweetened condensed milk', 321, 8.1, 54.4, 8.7, 0.0, 61, FALSE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Sữa đặc có đường');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Phô mai', 'Processed cheese', 371, 22.0, 2.6, 30.0, 0.0, 0, TRUE, FALSE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Phô mai');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bơ động vật', 'Butter', 717, 0.9, 0.1, 81.1, 0.0, 0, TRUE, FALSE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bơ động vật');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Trứng vịt', 'Duck egg', 185, 13.0, 1.5, 14.0, 0.0, 0, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Trứng vịt');

-- === HẠT & DẦU ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Hạt điều', 'Cashew nut', 553, 18.2, 30.2, 43.8, 3.3, 25, TRUE, TRUE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Hạt điều');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Hạt mè', 'Sesame seed', 573, 17.7, 23.5, 49.7, 11.8, 35, TRUE, TRUE, TRUE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Hạt mè');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Hạt bí', 'Pumpkin seed', 559, 30.2, 10.7, 49.1, 6.0, 25, TRUE, TRUE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Hạt bí');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Hạt dưa', 'Watermelon seed', 600, 28.3, 15.3, 47.4, 0.0, 0, TRUE, TRUE, FALSE, FALSE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Hạt dưa');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cùi dừa', 'Coconut meat', 354, 3.3, 15.2, 33.5, 9.0, 45, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cùi dừa');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Nước dừa', 'Coconut water', 19, 0.7, 3.7, 0.2, 1.1, 45, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Nước dừa');

-- === GIA VỊ & DẦU ĂN ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Nước mắm', 'Fish sauce', 35, 5.5, 3.5, 0.0, 0.0, 0, TRUE, FALSE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Nước mắm');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Dầu hào', 'Oyster sauce', 51, 0.9, 10.7, 0.5, 0.4, 0, TRUE, FALSE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Dầu hào');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Tương ớt', 'Chili sauce', 44, 0.8, 9.4, 0.3, 0.6, 0, TRUE, FALSE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Tương ớt');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Dầu mè', 'Sesame oil', 884, 0.0, 0.0, 100.0, 0.0, 0, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Dầu mè');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Dầu dừa', 'Coconut oil', 862, 0.0, 0.0, 100.0, 0.0, 0, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Dầu dừa');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Đường mía', 'Cane sugar', 387, 0.0, 100.0, 0.0, 0.0, 70, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Đường mía');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Mật ong', 'Honey', 304, 0.3, 82.4, 0.0, 0.2, 55, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Mật ong');

-- === MÓN ĂN VIỆT NAM ===
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Phở bò', 'Beef pho', 75, 5.5, 9.8, 1.5, 0.4, 45, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Phở bò');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bún bò Huế', 'Hue beef noodle soup', 90, 5.8, 11.5, 2.3, 0.5, 45, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bún bò Huế');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cơm tấm', 'Broken rice with pork', 175, 8.5, 26.5, 4.5, 0.8, 60, FALSE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cơm tấm');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Bánh xèo', 'Vietnamese sizzling crepe', 185, 5.2, 21.0, 9.5, 1.0, 55, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Bánh xèo');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Gỏi cuốn', 'Fresh spring roll', 120, 6.5, 16.0, 3.0, 1.5, 45, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Gỏi cuốn');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Chả giò', 'Fried spring roll', 248, 7.5, 23.0, 14.0, 1.5, 55, TRUE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Chả giò');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Canh chua cá', 'Vietnamese sour fish soup', 55, 5.0, 5.5, 1.5, 0.8, 20, TRUE, FALSE, FALSE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Canh chua cá');
INSERT INTO foods (name, name_en, calories, protein_g, carbs_g, fat_g, fiber_g, gi_index, ok_diabetes, ok_hypertension, ok_gout, ok_kidney, ok_celiac) SELECT 'Cháo trắng', 'Plain rice congee', 48, 1.2, 10.5, 0.1, 0.3, 68, FALSE, TRUE, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = 'Cháo trắng');
